version: "3.9"

services:

  sql_db:
    image: mysql:8
    container_name: sql_db
    restart: always
    ports:
      - "3309:3306"
    environment:
      - MYSQL_PASSWORD=jim
      - MYSQL_ROOT_PASSWORD=jim
      - MYSQL_USER=jim
      - MYSQL_DATABASE=todos 
    networks:
      - todo-network
    
  todolist:
    image:  n9064/ms-todolist:0.0.1-SNAPSHOT
    container_name: todolist
    ports: 
       - "8081:8080"
    depends_on:
      - sql_db
    networks:
      - todo-network
    environment:
      - SPRING_DATASOURCE_USERNAME=jim
      - SPRING_DATASOURCE_URL=jdbc:mysql://sql_db:3306/todos
      - SPRING_DATASOURCE_PASSWORD=jim

networks:
  todo-network:
    driver: bridge